scriptPath,detail,startTime,endTime,duration,result
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/get_messages_test.py,No exception in execute_script method.,2016-10-11 21:10:37.398576,2016-10-11 21:10:39.042851,0.6442749999999999,"{""result"":100,""messages"":[],""resultDesc"":""成功""}
10919
passed
passed
select * from ts_user_follow where userid_follow = '10919'
()
select * from ts_user_follow where userid_follow = '10919'
passed
"
,Exception in execute_script method: [Errno 2] No such file or directory: '',2016-10-11 21:10:39.043005,2016-10-11 21:10:39.043732,0.000727,
