scriptPath,detail,startTime,endTime,duration,result
,"Exception in execute_script method: file() argument 1 must be encoded string without NULL bytes, not str",2016-10-12 13:04:34.470025,2016-10-12 13:04:34.470114,8.9e-05,
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/collect_post_test.py,No exception in execute_script method.,2016-10-12 13:04:34.470880,2016-10-12 13:04:34.547792,0.076912,"Traceback (most recent call last):
  File ""/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/collect_post_test.py"", line 37, in <module>
    collect_assert(collect_post_test('runcheck5@163.com','1132664','1'))
  File ""/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/collect_post_test.py"", line 12, in collect_post_test
    s = requests.Session()
NameError: global name 'requests' is not defined
"
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/follow_test.py,No exception in execute_script method.,2016-10-12 13:04:34.547892,2016-10-12 13:04:35.603984,0.056091999999999996,"passed
passed
passed
"
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/get_followers_test.py,No exception in execute_script method.,2016-10-12 13:04:35.604087,2016-10-12 13:04:38.041483,0.437396,"passed
passed
passed
passed
passed
passed
passed
passed
passed
passed
passed
passed
passed
passed
"
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/get_posts_test.py,No exception in execute_script method.,2016-10-12 13:04:38.041588,2016-10-12 13:04:38.691316,0.649728,"passed
passed
passed
"
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/get_user_flower_cnt_test.py,No exception in execute_script method.,2016-10-12 13:04:38.691416,2016-10-12 13:04:39.231259,0.539843,"passed
passed
passed
"
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/get_user_header_test.py,No exception in execute_script method.,2016-10-12 13:04:39.231357,2016-10-12 13:04:39.307180,0.075823,"Traceback (most recent call last):
  File ""/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/get_user_header_test.py"", line 41, in <module>
    basic_assert(get_user_header_test('runcheck5@163.com'))
  File ""/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/get_user_header_test.py"", line 11, in get_user_header_test
    s = requests.Session()
NameError: global name 'requests' is not defined
"
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/gift_flower_test.py,No exception in execute_script method.,2016-10-12 13:04:39.307286,2016-10-12 13:04:40.209987,0.902701,"passed
passed
"
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/like_test.py,No exception in execute_script method.,2016-10-12 13:04:40.210084,2016-10-12 13:04:41.298185,0.088101,"passed
passed
passed
passed
"
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/my_collect_posts_test.py,No exception in execute_script method.,2016-10-12 13:04:41.298283,2016-10-12 13:04:41.860545,0.5622619999999999,"passed
passed
passed
passed
passed
"
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/post_info_test.py,No exception in execute_script method.,2016-10-12 13:04:41.860645,2016-10-12 13:04:42.935082,0.074437,"passed
passed
passed
passed
passed
"
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/search_users_test.py,No exception in execute_script method.,2016-10-12 13:04:42.935180,2016-10-12 13:04:43.495806,0.560626,"passed
passed
passed
"
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/send_post_test.py,No exception in execute_script method.,2016-10-12 13:04:43.495902,2016-10-12 13:04:44.029425,0.533523,"failed
failed
"
